// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNote struct {
	Title string `json:"title"`
}

type Note struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
}

type NoteUpdate struct {
	ID     string `json:"id"`
	Title  string `json:"title"`
	Status string `json:"status"`
}
