// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewNote struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Note struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type NoteUpdate struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}
