apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - image: gateway-service-image:latest
          name: gateway-service
          env:
            - name: NOTE_SERVICE_ENDPOINT
              value: note-service:443
            - name: ALLOWED_ORIGIN
              value: http://localhost:3000
          envFrom:
            - configMapRef:
                name: gcp-app-env
            - configMapRef:
                name: dev-env


