apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: kube-system
spec:
  selector:
    app: gateway-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - image: gateway-service-image:latest
          name: gateway-service
          env:
            - name: NOTE_SERVICE_ENDPOINT
              value: note-service:8008
