apiVersion: v1
kind: Service
metadata:
  name: note-service
  namespace: kube-system
spec:
  selector:
    app: note-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
        - image: note-service-image:latest
          name: note-service
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: serv
            - name: DB_NAME
              value: micro_serv
