apiVersion: v1
kind: Service
metadata:
  name: note-service
spec:
  selector:
    app: note-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-service
spec:
  selector:
    matchLabels:
      app: note-service
  template:
    metadata:
      labels:
        app: note-service
    spec:
      containers:
        - image: note-service-image:latest
          name: note-service
          envFrom:
            - configMapRef:
                name: gcp-app-env
            - configMapRef:
                name: dev-env
